export const SYSTEM_CONFIG = {
  systemName: 'Barangay Management System',
  version: '1.0.0',
  barangayInfo: {
    name: 'Barangay Darasa',
    municipality: 'Tanauan City',
    province: 'Batangas',
    region: 'CALABARZON - Region IV-A',
    contactNumber: '+63 917 123 4567',
    email: 'barangaydarasa@gmail.com',
    address: '123 Barangay Hall Road, Darasa, Tanauan City, Batangas',
    captainName: 'Juan Dela Cruz',
    secretaryName: 'Maria Santos',
    treasurerName: 'Pedro Reyes',
  },
  documentFees: {
    barangay_clearance: 50.00,
    certificate_of_residency: 30.00,
    certificate_of_indigency: 0.00,
    business_clearance: 500.00,
    good_moral_certificate: 50.00,
    first_time_job_seeker: 0.00,
    solo_parent_certificate: 0.00,
    cohabitation_certificate: 50.00,
    barangay_id: 50.00,
  },
  roles: [
    { value: 'super_admin', label: 'Super Admin' },
    { value: 'barangay_captain', label: 'Barangay Captain' },
    { value: 'secretary', label: 'Secretary' },
    { value: 'treasurer', label: 'Treasurer' },
    { value: 'kagawad', label: 'Kagawad' },
    { value: 'staff', label: 'Staff' },
    { value: 'resident', label: 'Resident' },
  ],
  documentTypes: [
    { value: 'barangay_clearance', label: 'Barangay Clearance' },
    { value: 'certificate_of_residency', label: 'Certificate of Residency' },
    { value: 'certificate_of_indigency', label: 'Certificate of Indigency' },
    { value: 'business_clearance', label: 'Business Clearance' },
    { value: 'good_moral_certificate', label: 'Good Moral Certificate' },
    { value: 'first_time_job_seeker', label: 'First Time Job Seeker Certificate' },
    { value: 'solo_parent_certificate', label: 'Solo Parent Certificate' },
    { value: 'cohabitation_certificate', label: 'Cohabitation Certificate' },
  ],
  civilStatus: ['Single', 'Married', 'Widowed', 'Separated', 'Divorced'],
  gender: ['Male', 'Female', 'Other'],
  religions: [
    'Roman Catholic',
    'Islam',
    'Iglesia ni Cristo',
    'Born Again Christian',
    'Buddhist',
    'Other',
  ],
};
